server:
  port: 80

spring:
  flyway:
    url: ${JDBC_DATASOURCE_URL}
    user: ${JDBC_DATASOURCE_USERNAME}
    password: ${JDBC_DATASOURCE_PASSWORD}

  datasource:
    url: ${JDBC_DATASOURCE_URL}
    username: ${JDBC_DATASOURCE_USERNAME}
    password: ${JDBC_DATASOURCE_PASSWORD}

jwt:
  secret: ${SECRET_KEY}
  expiration: 86400