server:
  port: 80

spring:
  flyway:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5500/finances}
    user: ${SPRING_DATASOURCE_USERNAME:ilia}
    password: ${SPRING_DATASOURCE_PASSWORD:gjkbnt[}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5500/finances}
    username: ${SPRING_DATASOURCE_USERNAME:ilia}
    password: ${SPRING_DATASOURCE_PASSWORD:gjkbnt[}

jwt:
  secret: ${SECRET_KEY}
  expiration: 86400