version: '3.1'

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:11
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${DB_ADMIN_USER}
      - POSTGRES_PASSWORD=${DB_ADMIN_PASS}
    ports:
      - "5500:5432"