create table user_account
(
    id       integer generated by default as identity
        constraint user_account_pkey
            primary key,
    login    varchar(255)
        constraint uniq_login
            unique,
    name     varchar(255),
    password varchar(255)
);

alter table user_account
    owner to ilia;

create table money_transaction
(
    id       integer generated by default as identity
        constraint money_transaction_pkey
            primary key,
    amount   bigint,
    title    varchar(255),
    date     timestamp,
    is_coast boolean,
    user_id  integer
        constraint foreign_key_for_user_account
            references user_account
);

alter table money_transaction
    owner to ilia;

insert into user_account (login, name, password)
values ('admin', 'admin', 'admin')